
debug: true
logLevel: 'debug'

serial:
  port: '/dev/ttyUSB_RFX'

mqtt:
  server: 'mqtt://192.168.xx.xx'
  username: 'xxxxxxx'
  password: 'xxxxxxx'
  base_topic: rfxcom        # optional, base MQTT topic

temperaturehumidity1:
  topic: temphumi
  devices:
    '0xCC07': 'Oregon Chambre Sud'
    '0xFD04': 'Oregon Salle de Bains'
    '0x7E08': 'Oregon Chambre Rue'
    '0x5901': 'Oregon Salle dO'
    '0xFC09': 'Oregon Bureau SSol'
    '0x7402': 'Oregon Grenier'

rain1:
  topic: rain
  devices:
    '0xFB00': 'Pluviomètre Facade'
